# Generated by Django 5.2.6 on 2025-09-24 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/cards/'),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/promos/'),
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='products/media/')),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_gallery', to='shop.product')),
            ],
        ),
    ]
