# Generated by Django 5.2.6 on 2025-09-26 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_review_media_reviewmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='shop.quiz'),
        ),
    ]
