# Generated by Django 5.2.6 on 2025-09-26 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_quizresult_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswer',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='shop.quiz'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='answer_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='shop.quizquestion'),
        ),
    ]
