# Generated by Django 5.2.6 on 2025-09-30 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_quiz_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arexperience',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_experience', to='shop.product'),
        ),
    ]
