# Generated by Django 5.2.6 on 2025-10-07 02:11

import django.utils.timezone
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_arexperience_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='category',
            field=models.CharField(choices=shop.models.get_category_choices, default='Fresh', max_length=50),
        ),
    ]
