# Generated by Django 5.2.6 on 2025-10-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_arexperience_marker_mind_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arexperience',
            name='marker_mind_url',
        ),
        migrations.RemoveField(
            model_name='arexperience',
            name='model_glb_url',
        ),
        migrations.AddField(
            model_name='arexperience',
            name='marker_mind',
            field=models.FileField(blank=True, help_text='Upload the compiled .mind file for MindAR tracking.', null=True, upload_to='ar/mind/'),
        ),
        migrations.AddField(
            model_name='arexperience',
            name='model_glb',
            field=models.FileField(blank=True, help_text='Upload the exported GLB model file.', null=True, upload_to='ar/models/'),
        ),
        migrations.AlterField(
            model_name='arexperience',
            name='viewer_url',
            field=models.CharField(blank=True, help_text='Frontend page that loads the AR viewer (e.g. /arview/eleganza).', max_length=255, null=True),
        ),
    ]
