# Generated by Django 5.2.6 on 2025-10-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_arexperience_marker_mind_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arexperience',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Optional background music (MP3/WAV) to play with AR scene.', null=True, upload_to='ar/audio/'),
        ),
        migrations.AddField(
            model_name='arexperience',
            name='video_file',
            field=models.FileField(blank=True, help_text='Optional video (MP4/WebM) to play in AR scene.', null=True, upload_to='ar/videos/'),
        ),
        migrations.AlterField(
            model_name='arexperience',
            name='marker_image',
            field=models.ImageField(blank=True, null=True, upload_to='ar/markers/'),
        ),
        migrations.AlterField(
            model_name='arexperience',
            name='marker_mind',
            field=models.FileField(blank=True, null=True, upload_to='ar/mind/'),
        ),
        migrations.AlterField(
            model_name='arexperience',
            name='model_glb',
            field=models.FileField(blank=True, null=True, upload_to='ar/models/'),
        ),
        migrations.AlterField(
            model_name='arexperience',
            name='viewer_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
