# Generated by Django 5.2.6 on 2025-10-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_retailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arexperience',
            name='viewer_url',
        ),
        migrations.AddField(
            model_name='arexperience',
            name='app_download_url',
            field=models.CharField(blank=True, help_text='Link to download or open the AR app (APK / Play Store / App Store).', max_length=255, null=True),
        ),
    ]
