# Generated by Django 5.2.6 on 2025-11-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_arexperience_app_download_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='target',
            field=models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('UNISEX', 'Unisex')], default='UNISEX', help_text='Primary audience / positioning.', max_length=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='allowed_products',
            field=models.ManyToManyField(blank=True, help_text='If set, only these products can be recommended by this quiz.', related_name='quizzes_whitelist', to='shop.product'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='audience',
            field=models.CharField(choices=[('ANY', 'Any'), ('MEN', 'Men'), ('WOMEN', 'Women'), ('UNISEX', 'Unisex')], default='ANY', help_text='If set, recommendations will be filtered by product.target.', max_length=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='label',
            field=models.CharField(blank=True, help_text="Optional badge, e.g. 'For Women', 'Gift Finder', 'Unisex Only'.", max_length=100),
        ),
    ]
