# Generated by Django 5.2.6 on 2025-11-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_payment_status_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
