# Generated by Django 5.2.6 on 2025-12-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_user_address_line2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScentPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text="Must match an existing Product.category (e.g. 'Fresh', 'Floral').", max_length=100, unique=True)),
                ('persona_name', models.CharField(max_length=150)),
                ('tagline', models.TextField(blank=True)),
                ('scent_notes', models.JSONField(blank=True, default=list)),
                ('occasions', models.JSONField(blank=True, default=list)),
                ('image', models.ImageField(blank=True, help_text='Square/portrait image representing this persona.', null=True, upload_to='personas/')),
                ('cover_image', models.ImageField(blank=True, help_text='Wide background image for quiz result hero.', null=True, upload_to='personas/covers/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
