# Generated by Django 5.2.6 on 2025-12-08 12:57

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_scentpersona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scentpersona',
            name='category',
            field=models.CharField(choices=shop.models.get_category_choices, help_text='Choose one of the existing Product.category values.', max_length=100, unique=True),
        ),
    ]
