# Generated by Django 5.2.6 on 2026-06-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_arexperience_app_download_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arexperience',
            name='app_download_file',
            field=models.FileField(blank=True, null=True, upload_to='ar/apk/'),
        ),
        migrations.AlterField(
            model_name='arexperience',
            name='marker_image',
            field=models.ImageField(blank=True, null=True, upload_to='ar/markers/'),
        ),
        migrations.AlterField(
            model_name='arexperience',
            name='marker_mind',
            field=models.FileField(blank=True, null=True, upload_to='ar/mind/'),
        ),
        migrations.AlterField(
            model_name='arexperience',
            name='model_glb',
            field=models.FileField(blank=True, null=True, upload_to='ar/models/'),
        ),
    ]
