# Generated by Django 5.2.6 on 2025-09-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('TO_PAY', 'To Pay'), ('TO_SHIP', 'To Ship'), ('TO_RECEIVE', 'To Receive'), ('TO_RATE', 'To Rate'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='TO_PAY', max_length=20),
        ),
    ]
