# Generated by Django 5.2.4 on 2025-09-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_image_product_card_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Malaysia', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='fullname',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='line1',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(default='00000', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
