# Generated by Django 5.2.6 on 2025-09-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_quizanswer_quiz_quizquestion_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='recommended_category',
            field=models.CharField(blank=True, choices=[('Fresh', 'Fresh'), ('Bold', 'Bold')], help_text='Which product category this answer points to', max_length=50, null=True),
        ),
    ]
