# Generated by Django 5.2.6 on 2025-09-26 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_quizanswer_recommended_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='recommended_category',
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='Fragrance Quiz', max_length=200),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='category',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Bold', 'Bold')], default='Fresh', max_length=50),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='shop.quiz'),
        ),
    ]
