# Generated by Django 5.2.6 on 2025-10-14 12:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_quizquestion_created_at_alter_quizanswer_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arexperience',
            options={'ordering': ['product', 'type'], 'verbose_name': 'AR Experience', 'verbose_name_plural': 'AR Experiences'},
        ),
        migrations.RemoveField(
            model_name='arexperience',
            name='description',
        ),
        migrations.RemoveField(
            model_name='arexperience',
            name='model_file',
        ),
        migrations.RemoveField(
            model_name='arexperience',
            name='video',
        ),
        migrations.AddField(
            model_name='arexperience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arexperience',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='arexperience',
            name='marker_image',
            field=models.ImageField(blank=True, help_text='Optional marker image (only used for marker-based AR)', null=True, upload_to='ar/markers/'),
        ),
        migrations.AddField(
            model_name='arexperience',
            name='type',
            field=models.CharField(choices=[('MARKER', 'Marker-based'), ('MARKERLESS', 'Markerless')], default='MARKER', help_text='Select whether this AR is marker-based or markerless', max_length=20),
        ),
        migrations.AddField(
            model_name='arexperience',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='arexperience',
            name='viewer_url',
            field=models.URLField(blank=True, help_text='Frontend page that loads the WebGL viewer (e.g. /arview or /arview-markerless)', null=True),
        ),
        migrations.AlterField(
            model_name='arexperience',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_experiences', to='shop.product'),
        ),
    ]
