# Generated by Django 5.2.6 on 2025-10-15 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_arexperience_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arexperience',
            name='marker_mind_url',
            field=models.URLField(blank=True, help_text='Public link to the .mind file for MindAR tracking.', null=True),
        ),
        migrations.AddField(
            model_name='arexperience',
            name='model_glb_url',
            field=models.URLField(blank=True, help_text='Public link to the exported GLB model.', null=True),
        ),
        migrations.AlterField(
            model_name='arexperience',
            name='marker_image',
            field=models.ImageField(blank=True, help_text='Marker image for user reference (optional preview).', null=True, upload_to='ar/markers/'),
        ),
        migrations.AlterField(
            model_name='arexperience',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_experience', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='arexperience',
            name='type',
            field=models.CharField(choices=[('MARKER', 'Marker-based'), ('MARKERLESS', 'Markerless')], default='MARKER', help_text='Select whether this AR uses a marker image or markerless tracking.', max_length=20),
        ),
        migrations.AlterField(
            model_name='arexperience',
            name='viewer_url',
            field=models.URLField(blank=True, help_text='Frontend page that loads the AR viewer (e.g. /arview/eleganza).', null=True),
        ),
    ]
