# Generated by Django 5.2.6 on 2025-10-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_arexperience_audio_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About GERAIN CHAN', help_text='Main heading for the About page.', max_length=150)),
                ('intro_text', models.CharField(blank=True, help_text='Short tagline or slogan under the title.', max_length=255, null=True)),
                ('body_text', models.TextField(help_text='Main story or description of the brand.')),
                ('mission', models.TextField(blank=True, help_text='Optional mission statement.', null=True)),
                ('vision', models.TextField(blank=True, help_text='Optional vision or philosophy.', null=True)),
                ('hero_image', models.ImageField(blank=True, help_text='Main banner or background image.', null=True, upload_to='site/about/hero/')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='Optional list of extra image URLs or paths.')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Example: {"instagram": "...", "facebook": "...", "tiktok": "..."}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site About',
                'verbose_name_plural': 'Site About',
                'ordering': ['-updated_at'],
            },
        ),
    ]
