# Generated by Django 5.2.6 on 2025-10-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_siteabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteabout',
            name='body_text',
            field=models.TextField(blank=True, help_text='Main story or description of the brand.', null=True),
        ),
    ]
