# Generated by Django 5.2.6 on 2025-10-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_siteabout_body_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteabout',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of extra image URLs or paths.', null=True),
        ),
        migrations.AlterField(
            model_name='siteabout',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Example: {"instagram": "...", "facebook": "...", "tiktok": "..."}', null=True),
        ),
        migrations.AlterField(
            model_name='siteabout',
            name='title',
            field=models.CharField(blank=True, default='About GERAIN CHAN', help_text='Main heading for the About page.', max_length=150, null=True),
        ),
    ]
