# Generated by Django 5.2.6 on 2025-10-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_siteabout_gallery_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteabout',
            name='social_icons',
            field=models.JSONField(blank=True, default=dict, help_text='Example: {"instagram": "/media/site/about/icons/insta.png"}', null=True),
        ),
        migrations.AlterField(
            model_name='siteabout',
            name='body_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteabout',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='siteabout',
            name='intro_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteabout',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteabout',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Example: {"instagram": "...", "facebook": "..."}', null=True),
        ),
        migrations.AlterField(
            model_name='siteabout',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
