# Generated by Django 5.2.6 on 2025-10-20 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_siteabout_social_icons_alter_siteabout_body_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('opening_time', models.TimeField(default=django.utils.timezone.now)),
                ('closing_time', models.TimeField(default=django.utils.timezone.now)),
                ('is_open_24h', models.BooleanField(default=False, help_text='Tick if open 24 hours')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('map_url', models.URLField(blank=True, help_text='Optional Google Maps link', null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload a photo of the retailer (e.g. storefront or logo)', null=True, upload_to='retailers/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
