# Generated by Django 5.2.6 on 2025-10-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_remove_arexperience_viewer_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arexperience',
            name='app_download_url',
        ),
        migrations.AddField(
            model_name='arexperience',
            name='app_download_file',
            field=models.FileField(blank=True, help_text='Upload the AR mobile app (.apk) for Android users.', null=True, upload_to='ar/apk/'),
        ),
    ]
