# Generated by Django 5.2.6 on 2025-12-20 13:11

import backend.r2_storage
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_scentpersona_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arexperience',
            name='app_download_file',
            field=models.FileField(blank=True, null=True, storage=backend.r2_storage.R2Storage(), upload_to='ar/apk/'),
        ),
        migrations.AlterField(
            model_name='arexperience',
            name='marker_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='ar/markers/'),
        ),
        migrations.AlterField(
            model_name='arexperience',
            name='marker_mind',
            field=models.FileField(blank=True, null=True, storage=backend.r2_storage.R2Storage(), upload_to='ar/mind/'),
        ),
        migrations.AlterField(
            model_name='arexperience',
            name='model_glb',
            field=models.FileField(blank=True, null=True, storage=backend.r2_storage.R2Storage(), upload_to='ar/models/'),
        ),
    ]
